version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "
        until pg_isready -h db -p 5432; do
          echo 'Waiting for Postgres...';
          sleep 2;
        done &&
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py test &&
        gunicorn mozio_backend.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgis/postgis:14-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres_data:
